### ISSUE TITLE
Jupyter unsupported for ipykernel versions > 4.3

### ISSUE THREAD

**Issue by newlawrence** [vgvassilev/cling#110]
Everything was ok until **ipykernel** versions 4.4 and 4.5 were released. Since then I'm getting the following error:
```
~ $ jupyter console --kernel cling
Traceback (most recent call last):
  File "/Users/alberto/anaconda/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 291, in main
    ClingKernelApp.launch_instance()
  File "/Users/alberto/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/Users/alberto/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/alberto/anaconda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 454, in initialize
    self.init_kernel()
  File "/Users/alberto/anaconda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 373, in init_kernel
    self.displayhook.get_execution_count = lambda: kernel.execution_count
AttributeError: 'ClingKernelApp' object has no attribute 'displayhook'
```

Digging inside the **ipykernel** I've found that the error starts from [this commit](https://github.com/ipython/ipykernel/commit/67ffacf144df609e39d041fa4570b7faac6485ef), which basically fixes a crash with another kernel.

I've found a simple solution that consists in replacing:
```python
self.displayhook.get_execution_count = lambda: kernel.execution_count
```

With:
```python
if hasattr(self, 'displayhook'):
    self.displayhook.get_execution_count = lambda: kernel.execution_count
```

But I don't known if it's a specific issue from this project or from **ipykernel** as I lack the knowledge of how all this **Jupyter** kernels stuff works. If you think this an issue from **ipykernel** I'll go report it there.

**Comment by vgvassilev** [comment]
Thanks for letting us know. That should be fixed in the master. Please reopen if this is not the case.
