### ISSUE TITLE
TypeError: readlink: can't specify None for path argument

### ISSUE THREAD

**Issue by stilist80** [vgvassilev/cling#123]
Hello,

I permanently receive TypeError in Jupyter terminal while trying to start cling kernel.
The following are predecessors:
01:32:04.628 NotebookApp] Timeout waiting for kernel_info reply from 81762983-2e89-47dc-a6f6-5f36d4f25865
[I 01:32:06.539 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 81762983-2e89-47dc-a6f6-5f36d4f25865 restarted
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/Alexey/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/Users/Alexey/cling/share/cling/Jupyter/kernel/clingkernel.py", line 317, in main
    ClingKernelApp.launch_instance()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 421, in initialize
    self.init_kernel()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 360, in init_kernel
    user_ns=self.user_ns,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/Users/Alexey/cling/share/cling/Jupyter/kernel/clingkernel.py", line 80, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: can't specify None for path argument

**Comment by vgvassilev** [comment]
@erlanger or @SylvainCorlay may be able to help.

**Comment by diimdeep** [comment]
```
[I 13:24:11.883 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 7b1e3302-570f-46c6-bd87-f703cc596f33 restarted
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/wolf/.local/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/Users/wolf/.local/share/cling/Jupyter/kernel/clingkernel.py", line 317, in main
    ClingKernelApp.launch_instance()
  File "/usr/local/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/usr/local/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 421, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 360, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/Users/wolf/.local/share/cling/Jupyter/kernel/clingkernel.py", line 80, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: can't specify None for path argument
[W 13:24:14.892 NotebookApp] KernelRestarter: restart failed
[W 13:24:14.892 NotebookApp] Kernel 7b1e3302-570f-46c6-bd87-f703cc596f33 died, removing from map.
```

**Comment by diimdeep** [comment]
```
whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: can't specify None for path argument
```

Solution is to make sure `cling` available in current terminal session `export PATH=/cling-install-prefix/bin:$PATH`

**Comment by vgvassilev** [comment]
@diimdeep, thanks for the proposed solution! @stilist80 please let us know if this doesn't solve it for you.

**Comment by IonizingRadiation** [comment]
@vgvassilev I got the same issue with @stilist80 , and I followed @diimdeep 's steps but end with no effect. I find that when I run `jupyter-notebook` in console, everything works pretty well, but the issue above occurs when I start `jupyter-notebook` through either `systemd` or `supervisor`. I am just confused.
Also I added `/usr/local/cling/bin` to both `/etc/bash.bashrc` and `~/.bashrc`.
Could anyone give some help?

Here is the log:
```
[I 2017-12-04 00:51:40.916 NotebookApp] Kernel started: 6635cccd-01e6-4b13-9946-21cbe2637366
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: can't specify None for path argument
[I 2017-12-04 00:51:43.908 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: can't specify None for path argument
[I 2017-12-04 00:51:46.914 NotebookApp] KernelRestarter: restarting kernel (2/5)
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: can't specify None for path argument
[I 2017-12-04 00:51:49.920 NotebookApp] KernelRestarter: restarting kernel (3/5)
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: can't specify None for path argument
[W 2017-12-04 00:51:51.346 NotebookApp] Timeout waiting for kernel_info reply from 6635cccd-01e6-4b13-9946-21cbe2637366
[I 2017-12-04 00:51:52.925 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 6635cccd-01e6-4b13-9946-21cbe2637366 restarted
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: can't specify None for path argument
[W 2017-12-04 00:51:55.932 NotebookApp] KernelRestarter: restart failed
[W 2017-12-04 00:51:55.933 NotebookApp] Kernel 6635cccd-01e6-4b13-9946-21cbe2637366 died, removing from map.
ERROR:root:kernel 6635cccd-01e6-4b13-9946-21cbe2637366 restarted failed!
```

The `jupyter.service` in `/etc/systemd/system/`:
```
[Unit]
Description=Jupyter Notebook
After=network.target

[Service]
Type=simple
PIDFile=/var/run/jupyter.pid
ExecStart=/usr/local/bin/jupyter-notebook --config=/home/jupyter/.jupyter/jupyter_notebook_config.py
User=jupyter
WorkingDirectory=/home/jupyter/notebook/
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```
The `jupyter.conf` in `/etc/supervisor/conf.d`:
```
[program:jupyter]
command = jupyter notebook --config=/home/jupyter/.jupyter/jupyter_notebook_config.py
directory = /home/jupyter/notebook/
user = jupyter
autostart = true
autorestart = true
stdout_logfile = /home/jupyter/notebook/log
redirect_stderr = true
```

Here are the information of my machine:
OS: Ubuntu 16.04 x86_64
RAM: 512M
CPU: 1x Intel Xeon
And here are what I referred to install `jupyter` and `cling`:

**Comment by IonizingRadiation** [comment]
I find a solution to it:
The `supervisor` or `systemd` does not import `$PATH` from `/etc/bash.bashrc` or `~/.bashrc` which result in that error. I referred the [wiki](https://wiki.archlinux.org/index.php/Systemd/User) and run the commands below:
```
sudo systemctl import-environment PATH
sudo systemctl restart jupyter
```
Then the cling kernel can run well.
Also I came across another issue that when running `cling '#include <iostream>'`, it returns `ERROR in cling::CIFactory::createCI():
  resource directory /usr/local/cling/bin/../lib/clang/5.0.0 not found! ... /usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found`. I got to solve it by `sudo chmod +x /usr/local/cling/lib/*`.
Thanks for author's awesome work.
