### ISSUE TITLE
Python kernel implementation: "Bad file descriptor" 

### ISSUE THREAD

**Issue by SylvainCorlay** [vgvassilev/cling#138]
```bash
[ClingKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "miniconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "miniconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "miniconda3/lib/python3.5/site-packages/clingkernel.py", line 247, in do_execute
    with self.forward_stream('stdout'), self.forward_stream('stderr'):
  File "miniconda3/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "miniconda3/lib/python3.5/site-packages/clingkernel.py", line 191, in forward_stream
    save_fd = os.dup(real_fd)
OSError: [Errno 9] Bad file descriptor
```

**Comment by shyam-jagannathan** [comment]
Hi,

Is there any solution to this problem? Please help not sure how to get around it.
