### ISSUE TITLE
Get an error when trying to create deb packages

### ISSUE THREAD

**Issue by Trophime** [vgvassilev/cling#139]
Hi,
I tried to build a debian package on Debian/Testing using the following command line:
```
./cpt.py  --current-dev=deb --create-dev-env Release --with-workdir=./cling-build/
```

The build went smoothly but I end up with an error when trying to create deb packages:
```
──────────────────────────────────────────────────────────────────────────────┐
│ Set up the debian directory                                                  │
└──────────────────────────────────────────────────────────────────────────────┘
Create directory: debian
Create directory: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/source
Create file: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/source/format
Create file: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/source/lintian-overrides
Create file: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/cling.install
Create file: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/compact
Create file: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/compat
Create file: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/control
Create file: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/copyright
Create file: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/rules
Create file: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/changelog
subprocess.CalledProcessError: Command 'git log v0.3...HEAD --format=  * %s | fmt -s' returned non-zero exit status 128



┌──────────────────────────────────────────────────────────────────────────────┐
│ Clean up                                                                     │
└──────────────────────────────────────────────────────────────────────────────┘
Skipping build directory: /home/LNCMI-G/trophime/cling-build/builddir
Remove directory: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f
Create output directory: /home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f-1
Traceback (most recent call last):
  File "./cpt.py", line 1967, in <module>
    debianize()
  File "./cpt.py", line 897, in debianize
    f = open(os.path.join(prefix, 'debian', 'changelog'), 'a+')
IOError: [Errno 2] No such file or directory: u'/home/LNCMI-G/trophime/cling-build/cling-0.4~dev-f1def4f/debian/changelog'
``` 

Best
C

**Comment by onyb** [comment]
@Trophime It might be that you don't have GNU coreutils package installed on your machine. Could you please check?

**Comment by Trophime** [comment]
Hi, it seems that I have coreutils installed:
```
ii  coreutils                                 8.26-2                                 amd64        GNU core utilities
```

**Comment by vgvassilev** [comment]
And I assume you have installed git?

**Comment by Trophime** [comment]
yes.
I take a look at the error:
* Seems like adding a test for existing ```prefix``` directory fix this issue (strange). 
* But then I run into an other pb ```STABLE_TAG``` seems not to be initialized 
* and finaly I have pb with malformatted ```debian/changelog```. 

This may be linked to the ``git``` error from ```git log v' + TAG + ' HEAD --format="  * %s" | fmt -s```

**Comment by Trophime** [comment]
I followed instructions from section [Building from Source with Cling Packaging](https://github.com/vgvassilev/cling)

**Comment by Trophime** [comment]
The trouble for malformatted ```debian/changelog``` is related with my own configuration.
```gpg --fingerprint | grep uid | sed s/"uid *"//g``` returns several instead of 1, I guess.

**Comment by vgvassilev** [comment]
Hm, isn't returning more than 1 result fine? If you fixed it on your end could you submit a PR?

**Comment by vgvassilev** [comment]
I think this issue was resolved. Thanks for reporting.
