### ISSUE TITLE
Binary snapshots 404

### ISSUE THREAD

**Issue by Manouchehri** [vgvassilev/cling#92]
The link https://ecsft.cern.ch/dist/cling given in README.md seems to be down?

![image](https://cloud.githubusercontent.com/assets/7232674/16543491/5e5fec3c-40a5-11e6-91bf-c0b7ca0a4a93.png)

**Comment by Manouchehri** [comment]
Breaks the packaging tool too.

```bash
ubuntu@DESKTOP-3RQO5S5:~$ python cpt.py --current-dev CURRENT_DEV
Cling Packaging Tool (CPT)
Arguments vector: ['cpt.py', '--current-dev', 'CURRENT_DEV']

╔══════════════════════════════════════════════════════════════════════════════╗
║ cling (x86_64)                               Sat, 02 Jul 2016 22:37:36 -0400 ║
╚══════════════════════════════════════════════════════════════════════════════╝
Thread Model: POSIX
Operating System: Linux
Distribution: Ubuntu
Release: xenial
Revision: 16.04
Architecture: x86_64

┌──────────────────────────────────────────────────────────────────────────────┐
│ Fetch source files                                                           │
└──────────────────────────────────────────────────────────────────────────────┘
Last known good LLVM revision is: 214630
Current working directory is: /home/ubuntu/ec/build

Fetching LLVM ...
  HTTP request sent, awaiting response ...
Traceback (most recent call last):
  File "cpt.py", line 1650, in <module>
    fetch_llvm(llvm_revision)
  File "cpt.py", line 190, in fetch_llvm
    out_dir=workdir)
  File "cpt.py", line 137, in wget
    u = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by Manouchehri** [comment]
Oops, duplicate of #80 and #81..

**Comment by CrazyPython** [comment]
@Manouchehri  Please close this issue.
